#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/m2/repository ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir m2/repository                
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir logs
fi

cd $OPENSHIFT_REPO_DIR/backend/threesixtytool

export MAVEN_OPTS="-Xms384m -Xmx412m"

mvn -s settings.xml -Popenshift clean install -DskipTests=true