#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

cd ~/app-deployments/current/
nohup java -Xms384m -Xmx412m -jar service-registry-1.0.0-SNAPSHOT.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} --spring.profiles.active=openshift &